version: '3.9'
services:
  emissor-avancado-debug:
    image: emissor-avancado:local
    environment:
      - DB_ADDRESS=db-arthur
      - DB_PORT=3306
      - SCHEMA_NAME=emissor_avancado
      - DB_USERNAME=dev
      - DB_PASSWORD=dev1234
      - TESSERACT_DATAPATH=/usr/share/tesseract-ocr/4.00/tessdata/
      - OMP_THREAD_LIMIT=1
      - TESSERACT_PAGE_SEGMENTATION_MODE=6
      - TESSERACT_OCR_ENGINE_MODE=1
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - internal-network-emissor-avancado
    command: java -jar emissor-avancado.jar
networks:
  internal-network-emissor-avancado:
    external: true