server:
  servlet:
    context-path: /advanced-certificate
  port: ${SERVER_PORT:8080}

hawa-ca-service:
  address: ${HAWA_ADDRESS:http://150.162.56.176:2901/hawa-ca/1}
  city: ${CITY:Florianopolis}
  state: ${STATE:SC}

key-service:
  key-size: ${RSA_KEY_SIZE:2048}
  key-algorithm: RSA

verifier-service:
  address: ${VERIFIER_ADDRESS:https://pbad.labsec.ufsc.br/verifier-hom/report}

tesseract-service:
  datapath: ${TESSERACT_DATAPATH:/usr/share/tesseract/tessdata}

dossier-service:
  key-store-filename: ${KEY_STORE_PATH:key-store.jks}
  key-entry: ${KEY_ENTRY:dossier-key}
  key-entry-password: ${KEY_ENTRY_PASSWORD:dossier-key-1234}
  key-store-password: ${KEY_STORE_PASSWORD:key-store-1234}

#usr/share/tesseract-ocr/4.00/tessdata/

spring:
  datasource:
    url: jdbc:mysql://${DB_ADDRESS:db-emissor-avancado}:${DB_PORT:2900}/${SCHEMA_NAME:emissor_avancado}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:dev1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

