server:
  servlet:
    context-path: /advanced-certificate

hawa-ca-service:
  address: ${HAWA_ADDRESS:http://150.162.56.176:2901/hawa-ca/1}
  city: ${CITY:Florianopolis}
  state: ${STATE:SC}

key-service:
  key-size: ${KEY_SIZE:2048}
  key-algorithm: ${KEY_ALGORITHM:RSA}

verifier-service:
  address: ${CNH_VERIFIER_ADDRESS:https://pbad.labsec.ufsc.br/verifier-hom/report}

tesseract-service:
  datapath: ${TESSERACT_DATAPATH:/usr/share/tesseract/tessdata}
